version: "3.8"

networks:
  meals-network:
    name: meals-network

services:
  meals-pg:
    container_name: meals-pg
    image: postgres:13-alpine
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-root}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-meals-pg}
    volumes:
      - meals-pg-volume:/var/lib/postgresql/data/
    networks:
      - meals-network
    restart: always

  meals-go:
    container_name: meals-go
    build:
      context: ..
      dockerfile: build/ci/Dockerfile.prod
    ports:
      - "${HTTP_PORT:-8000}:${HTTP_PORT:-8000}"
      - "2345:2345"
    networks:
      - meals-network
    depends_on:
      - meals-pg
      - meals-redis
      - meals-rabbit
    volumes:
      - ..:/app:rw,delegated
    restart: always

  meals-redis:
    container_name: meals-redis
    image: redis:alpine
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - meals-redis-volume:/data
    networks:
      - meals-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  meals-rabbit:
    container_name: "meals-rabbit"
    image: "rabbitmq:alpine"
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ Management UI port
    environment:
      RABBITMQ_ERLANG_COOKIE: "secretcookie"  # Change this to a secure value
    volumes:
      - meals-rabbit-volume:/var/lib/rabbitmq
    networks:
      - meals-network
    healthcheck:
      test: "rabbitmq-diagnostics -q ping"
      interval: 10s  # Adjust as needed
      timeout: 10s   # Adjust as needed
      retries: 3     # Adjust as needed

  meals-ls:
    container_name: "meals-ls"
    image: localstack/localstack
    ports:
      - "${LOCALSTACK_PORT:-4566}:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${LOCALSTACK_DEBUG:-0} # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
    volumes:
      - "meals-ls-volume:/var/lib/localstack"
      - "meals-ls-volume:/var/run/docker.sock:/var/run/docker.sock"

volumes:
  meals-pg-volume:
  meals-redis-volume:
  meals-ls-volume:
  meals-rabbit-volume:
    driver: local