// Code generated by mockery v2.41.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	requests "project-skbackend/internal/controllers/requests"

	responses "project-skbackend/internal/controllers/responses"

	uttoken "project-skbackend/packages/utils/uttoken"

	uuid "github.com/google/uuid"
)

// IAuthService is an autogenerated mock type for the IAuthService type
type IAuthService struct {
	mock.Mock
}

// ForgotPassword provides a mock function with given fields: req
func (_m *IAuthService) ForgotPassword(req requests.ForgotPassword) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(requests.ForgotPassword) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: req, ctx
func (_m *IAuthService) Login(req requests.Login, ctx *gin.Context) (*responses.User, *uttoken.TokenHeader, error) {
	ret := _m.Called(req, ctx)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *responses.User
	var r1 *uttoken.TokenHeader
	var r2 error
	if rf, ok := ret.Get(0).(func(requests.Login, *gin.Context) (*responses.User, *uttoken.TokenHeader, error)); ok {
		return rf(req, ctx)
	}
	if rf, ok := ret.Get(0).(func(requests.Login, *gin.Context) *responses.User); ok {
		r0 = rf(req, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.User)
		}
	}

	if rf, ok := ret.Get(1).(func(requests.Login, *gin.Context) *uttoken.TokenHeader); ok {
		r1 = rf(req, ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*uttoken.TokenHeader)
		}
	}

	if rf, ok := ret.Get(2).(func(requests.Login, *gin.Context) error); ok {
		r2 = rf(req, ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RefreshAuthToken provides a mock function with given fields: token, ctx
func (_m *IAuthService) RefreshAuthToken(token string, ctx *gin.Context) (*responses.User, *uttoken.TokenHeader, error) {
	ret := _m.Called(token, ctx)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAuthToken")
	}

	var r0 *responses.User
	var r1 *uttoken.TokenHeader
	var r2 error
	if rf, ok := ret.Get(0).(func(string, *gin.Context) (*responses.User, *uttoken.TokenHeader, error)); ok {
		return rf(token, ctx)
	}
	if rf, ok := ret.Get(0).(func(string, *gin.Context) *responses.User); ok {
		r0 = rf(token, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *gin.Context) *uttoken.TokenHeader); ok {
		r1 = rf(token, ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*uttoken.TokenHeader)
		}
	}

	if rf, ok := ret.Get(2).(func(string, *gin.Context) error); ok {
		r2 = rf(token, ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Register provides a mock function with given fields: req, ctx
func (_m *IAuthService) Register(req requests.Register, ctx *gin.Context) (*responses.User, *uttoken.TokenHeader, error) {
	ret := _m.Called(req, ctx)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *responses.User
	var r1 *uttoken.TokenHeader
	var r2 error
	if rf, ok := ret.Get(0).(func(requests.Register, *gin.Context) (*responses.User, *uttoken.TokenHeader, error)); ok {
		return rf(req, ctx)
	}
	if rf, ok := ret.Get(0).(func(requests.Register, *gin.Context) *responses.User); ok {
		r0 = rf(req, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.User)
		}
	}

	if rf, ok := ret.Get(1).(func(requests.Register, *gin.Context) *uttoken.TokenHeader); ok {
		r1 = rf(req, ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*uttoken.TokenHeader)
		}
	}

	if rf, ok := ret.Get(2).(func(requests.Register, *gin.Context) error); ok {
		r2 = rf(req, ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ResetPassword provides a mock function with given fields: req
func (_m *IAuthService) ResetPassword(req requests.ResetPassword) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(requests.ResetPassword) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResetPasswordEmail provides a mock function with given fields: id, token
func (_m *IAuthService) ResetPasswordEmail(id uuid.UUID, token string) error {
	ret := _m.Called(id, token)

	if len(ret) == 0 {
		panic("no return value specified for ResetPasswordEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) error); ok {
		r0 = rf(id, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAuthService creates a new instance of IAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuthService {
	mock := &IAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
