// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	models "project-skbackend/internal/models"

	mock "github.com/stretchr/testify/mock"

	utpagination "project-skbackend/packages/utils/utpagination"

	uuid "github.com/google/uuid"
)

// ICartRepository is an autogenerated mock type for the ICartRepository type
type ICartRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *ICartRepository) Create(c models.Cart) (*models.Cart, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Cart) (*models.Cart, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(models.Cart) *models.Cart); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(models.Cart) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: c
func (_m *ICartRepository) Delete(c models.Cart) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Cart) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: p
func (_m *ICartRepository) FindAll(p utpagination.Pagination) (*utpagination.Pagination, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 *utpagination.Pagination
	var r1 error
	if rf, ok := ret.Get(0).(func(utpagination.Pagination) (*utpagination.Pagination, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func(utpagination.Pagination) *utpagination.Pagination); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utpagination.Pagination)
		}
	}

	if rf, ok := ret.Get(1).(func(utpagination.Pagination) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByMealID provides a mock function with given fields: mid
func (_m *ICartRepository) FindByMealID(mid uuid.UUID) ([]*models.Cart, error) {
	ret := _m.Called(mid)

	if len(ret) == 0 {
		panic("no return value specified for FindByMealID")
	}

	var r0 []*models.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]*models.Cart, error)); ok {
		return rf(mid)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []*models.Cart); ok {
		r0 = rf(mid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(mid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByMemberID provides a mock function with given fields: mid
func (_m *ICartRepository) FindByMemberID(mid uuid.UUID) ([]*models.Cart, error) {
	ret := _m.Called(mid)

	if len(ret) == 0 {
		panic("no return value specified for FindByMemberID")
	}

	var r0 []*models.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]*models.Cart, error)); ok {
		return rf(mid)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []*models.Cart); ok {
		r0 = rf(mid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(mid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *ICartRepository) GetByID(id uuid.UUID) (*models.Cart, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Cart, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Cart); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByMealIDAndMemberID provides a mock function with given fields: membid, mealid
func (_m *ICartRepository) GetByMealIDAndMemberID(membid uuid.UUID, mealid uuid.UUID) (*models.Cart, error) {
	ret := _m.Called(membid, mealid)

	if len(ret) == 0 {
		panic("no return value specified for GetByMealIDAndMemberID")
	}

	var r0 *models.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (*models.Cart, error)); ok {
		return rf(membid, mealid)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) *models.Cart); ok {
		r0 = rf(membid, mealid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(membid, mealid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Read provides a mock function with given fields:
func (_m *ICartRepository) Read() ([]*models.Cart, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []*models.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Cart, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Cart); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c
func (_m *ICartRepository) Update(c models.Cart) (*models.Cart, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Cart) (*models.Cart, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(models.Cart) *models.Cart); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(models.Cart) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICartRepository creates a new instance of ICartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICartRepository {
	mock := &ICartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
