// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	requests "project-skbackend/internal/controllers/requests"
	responses "project-skbackend/internal/controllers/responses"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ICartService is an autogenerated mock type for the ICartService type
type ICartService struct {
	mock.Mock
}

// Create provides a mock function with given fields: req
func (_m *ICartService) Create(req requests.CreateCart) (*responses.Cart, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *responses.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(requests.CreateCart) (*responses.Cart, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(requests.CreateCart) *responses.Cart); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(requests.CreateCart) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *ICartService) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: id
func (_m *ICartService) FindByID(id uuid.UUID) (*responses.Cart, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *responses.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*responses.Cart, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *responses.Cart); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Read provides a mock function with given fields:
func (_m *ICartService) Read() ([]*responses.Cart, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []*responses.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*responses.Cart, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*responses.Cart); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*responses.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, req
func (_m *ICartService) Update(id uuid.UUID, req requests.UpdateCart) (*responses.Cart, error) {
	ret := _m.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *responses.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, requests.UpdateCart) (*responses.Cart, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, requests.UpdateCart) *responses.Cart); ok {
		r0 = rf(id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, requests.UpdateCart) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICartService creates a new instance of ICartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICartService {
	mock := &ICartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
