// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IConsumerService is an autogenerated mock type for the IConsumerService type
type IConsumerService struct {
	mock.Mock
}

// ConsumeMail provides a mock function with given fields:
func (_m *IConsumerService) ConsumeMail() {
	_m.Called()
}

// NewIConsumerService creates a new instance of IConsumerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIConsumerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IConsumerService {
	mock := &IConsumerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
