// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	models "project-skbackend/internal/models"

	mock "github.com/stretchr/testify/mock"

	utpagination "project-skbackend/packages/utils/utpagination"

	uuid "github.com/google/uuid"
)

// IIllnessRepository is an autogenerated mock type for the IIllnessRepository type
type IIllnessRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ill
func (_m *IIllnessRepository) Create(ill models.Illness) (*models.Illness, error) {
	ret := _m.Called(ill)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Illness
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Illness) (*models.Illness, error)); ok {
		return rf(ill)
	}
	if rf, ok := ret.Get(0).(func(models.Illness) *models.Illness); ok {
		r0 = rf(ill)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Illness)
		}
	}

	if rf, ok := ret.Get(1).(func(models.Illness) error); ok {
		r1 = rf(ill)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ill
func (_m *IIllnessRepository) Delete(ill models.Illness) error {
	ret := _m.Called(ill)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Illness) error); ok {
		r0 = rf(ill)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: p
func (_m *IIllnessRepository) FindAll(p utpagination.Pagination) (*utpagination.Pagination, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 *utpagination.Pagination
	var r1 error
	if rf, ok := ret.Get(0).(func(utpagination.Pagination) (*utpagination.Pagination, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func(utpagination.Pagination) *utpagination.Pagination); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utpagination.Pagination)
		}
	}

	if rf, ok := ret.Get(1).(func(utpagination.Pagination) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *IIllnessRepository) GetByID(id uuid.UUID) (*models.Illness, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Illness
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Illness, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Illness); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Illness)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Read provides a mock function with given fields:
func (_m *IIllnessRepository) Read() ([]*models.Illness, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []*models.Illness
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Illness, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Illness); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Illness)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ill
func (_m *IIllnessRepository) Update(ill models.Illness) (*models.Illness, error) {
	ret := _m.Called(ill)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Illness
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Illness) (*models.Illness, error)); ok {
		return rf(ill)
	}
	if rf, ok := ret.Get(0).(func(models.Illness) *models.Illness); ok {
		r0 = rf(ill)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Illness)
		}
	}

	if rf, ok := ret.Get(1).(func(models.Illness) error); ok {
		r1 = rf(ill)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIIllnessRepository creates a new instance of IIllnessRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIIllnessRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IIllnessRepository {
	mock := &IIllnessRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
