// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	requests "project-skbackend/internal/controllers/requests"

	mock "github.com/stretchr/testify/mock"
)

// IMailService is an autogenerated mock type for the IMailService type
type IMailService struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: req
func (_m *IMailService) SendEmail(req requests.SendEmail) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(requests.SendEmail) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendResetPasswordEmail provides a mock function with given fields: data
func (_m *IMailService) SendResetPasswordEmail(data requests.SendEmailResetPassword) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for SendResetPasswordEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(requests.SendEmailResetPassword) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendVerifyEmail provides a mock function with given fields: req
func (_m *IMailService) SendVerifyEmail(req requests.SendEmailVerification) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for SendVerifyEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(requests.SendEmailVerification) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIMailService creates a new instance of IMailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMailService {
	mock := &IMailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
