// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	models "project-skbackend/internal/models"

	mock "github.com/stretchr/testify/mock"

	requests "project-skbackend/internal/controllers/requests"

	responses "project-skbackend/internal/controllers/responses"

	utpagination "project-skbackend/packages/utils/utpagination"

	uuid "github.com/google/uuid"
)

// IOrganizationService is an autogenerated mock type for the IOrganizationService type
type IOrganizationService struct {
	mock.Mock
}

// Create provides a mock function with given fields: req
func (_m *IOrganizationService) Create(req requests.CreateOrganization) (*responses.Organization, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *responses.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(requests.CreateOrganization) (*responses.Organization, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(requests.CreateOrganization) *responses.Organization); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(requests.CreateOrganization) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *IOrganizationService) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: preq
func (_m *IOrganizationService) FindAll(preq utpagination.Pagination) (*utpagination.Pagination, error) {
	ret := _m.Called(preq)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 *utpagination.Pagination
	var r1 error
	if rf, ok := ret.Get(0).(func(utpagination.Pagination) (*utpagination.Pagination, error)); ok {
		return rf(preq)
	}
	if rf, ok := ret.Get(0).(func(utpagination.Pagination) *utpagination.Pagination); ok {
		r0 = rf(preq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utpagination.Pagination)
		}
	}

	if rf, ok := ret.Get(1).(func(utpagination.Pagination) error); ok {
		r1 = rf(preq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *IOrganizationService) GetByID(id uuid.UUID) (*responses.Organization, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *responses.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*responses.Organization, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *responses.Organization); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Read provides a mock function with given fields:
func (_m *IOrganizationService) Read() ([]*models.Organization, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []*models.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Organization, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Organization); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, req
func (_m *IOrganizationService) Update(id uuid.UUID, req requests.UpdateOrganization) (*responses.Organization, error) {
	ret := _m.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *responses.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, requests.UpdateOrganization) (*responses.Organization, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, requests.UpdateOrganization) *responses.Organization); ok {
		r0 = rf(id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, requests.UpdateOrganization) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIOrganizationService creates a new instance of IOrganizationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOrganizationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOrganizationService {
	mock := &IOrganizationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
