// Code generated by mockery v2.41.0. DO NOT EDIT.

package mocks

import (
	models "project-skbackend/internal/models"

	mock "github.com/stretchr/testify/mock"

	utpagination "project-skbackend/packages/utils/utpagination"

	uuid "github.com/google/uuid"
)

// IPartnerRepository is an autogenerated mock type for the IPartnerRepository type
type IPartnerRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: p
func (_m *IPartnerRepository) Create(p models.Partner) (*models.Partner, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Partner
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Partner) (*models.Partner, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func(models.Partner) *models.Partner); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Partner)
		}
	}

	if rf, ok := ret.Get(1).(func(models.Partner) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: p
func (_m *IPartnerRepository) Delete(p models.Partner) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Partner) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: p
func (_m *IPartnerRepository) FindAll(p utpagination.Pagination) (*utpagination.Pagination, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 *utpagination.Pagination
	var r1 error
	if rf, ok := ret.Get(0).(func(utpagination.Pagination) (*utpagination.Pagination, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func(utpagination.Pagination) *utpagination.Pagination); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utpagination.Pagination)
		}
	}

	if rf, ok := ret.Get(1).(func(utpagination.Pagination) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: pid
func (_m *IPartnerRepository) FindByID(pid uuid.UUID) (*models.Partner, error) {
	ret := _m.Called(pid)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Partner
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Partner, error)); ok {
		return rf(pid)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Partner); ok {
		r0 = rf(pid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Partner)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(pid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Read provides a mock function with given fields:
func (_m *IPartnerRepository) Read() ([]*models.Partner, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []*models.Partner
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Partner, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Partner); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Partner)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: p
func (_m *IPartnerRepository) Update(p models.Partner) (*models.Partner, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Partner
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Partner) (*models.Partner, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func(models.Partner) *models.Partner); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Partner)
		}
	}

	if rf, ok := ret.Get(1).(func(models.Partner) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIPartnerRepository creates a new instance of IPartnerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPartnerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPartnerRepository {
	mock := &IPartnerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
