name: Build and test

on:
  pull_request:
    branches:
      - main
      - stg
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go install ./...
      - name: Build
        run: go build -v ./...
      - name: Echo
        run: echo "Hello, world!"


  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go install ./...
      - name: Test with the Go CLI
        run: go test ./...