name: Deployment to staging

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          file: ../../build/ci/Dockerfile.prod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

      - name: Remote Access to Droplets
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script_stop: true
          command_timeout: 200m
          script: |
            docker pull ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
            rm -rf .env
            echo "SERVER_ENV=${{ secrets.SERVER_ENV }}" > .env
            docker stop ${{ vars.DOCKER_APP_NAME }} || true
            docker rm ${{ vars.DOCKER_APP_NAME }} || true
            docker run -d -p 7000:7000 \
            --name ${{ vars.DOCKER_APP_NAME }} \
            --env-file .env \
            --restart always \
            ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
            sudo systemctl reload nginx